set -o vi

bindkey '^R' history-incremental-search-backward

eval "$(~/tool/homebrew/bin/brew shellenv)"
export PATH=$PATH:/usr/local/texlive/2022basic/bin/universal-darwin
export PATH=$PATH:~/.cargo/bin
export PATH=$PATH:~/miniconda3/bin

export PATH_=$PATH

# Created by `pipx` on 2024-02-14 06:52:21
export PATH="$PATH:/Users/tosh/.local/bin"

export PYENV_ROOT="$HOME/.pyenv"
[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"
